Repository Aesthisia/LLMinator, pull requests merged in 2024-05, with the labels that each got.

#25 Select model from chat tab
  webui.py
Labels: Feature

#28 Update README.md with new features
  README.md
Labels: documentation

#29 feat: Add support for selecting execution provider, CPU or GPU with CUDA
  webui.py
Labels: Feature

#32 docs: Add installation and development tips, update
  README.md
Labels: documentation

#34 fix: dropdown for initially empty saved_gguf_models_list
  webui.py
Labels: bug

#35 fix: Model list not updating after download snapshot
  core.py
  webui.py
Labels: bug

#33 Enable LLM inference with llama.cpp and llama-cpp-python
  .gitignore
  CMakeLists.txt
  Makefile
  README.md
  __init__.py
  configs/config.ini
  core.py
  models/models.txt
  requirements.txt
  src/quantize.py
  webui.py
Labels: Feature

#37 feat: streaming support to chatbot
  webui.py
Labels: enhancement

#39 docs: Add youtube video link and fix typo
  README.md
Labels: documentation

#40 feat: Config tab to adjust generation params
  README.md
  style.css
  webui.py
Labels: Feature

#41 feat: text generation websocket functionality
  README.md
  example/index.html
  main.py
  requirements.txt
  webui.py
Labels: Feature

#46 fix: Remove shell=True
  src/quantize.py
Labels: bug

#47 chore(deps): Update llama-cpp-python to 0.2.76 (#44)
  requirements.txt
Labels: bug
