Repository Aesthisia/LLMinator, pull requests merged in 2024-04, with the labels that each got.

#11 Added requirements.txt
  requirements.txt
Labels: Feature

#13 Updated the image and added a command to install requirements.txt
  README.md
Labels: documentation

#14 Fixed typo 👾 in README.md
  README.md
Labels: bug

#16 Fix: Remove Cached Models
  core.py
  webui.py
Labels: bug

#18 Update default model repo id
  core.py
Labels: enhancement

#19 Implement config.ini for enhanced persistence of settings
  .gitignore
  configs/config.ini
  core.py
  webui.py
Labels: enhancement

#21 Implement command-line arguments for host, port and share
  README.md
  webui.py
Labels: Feature

#23 Add Models Tab UI for Model Conversion
  modelsui.py
  webui.py
Labels: Feature

#22 Feature/llamacpp
  .gitignore
  CMakeLists.txt
  Makefile
  README.md
  __init__.py
  requirements.txt
  src/quantize.py
  webui.py
Labels: Feature

#24 Feat: download and convert, select model from models tab
  configs/config.ini
  core.py
  modelsui.py
  requirements.txt
  src/quantize.py
  webui.py
Labels: Feature

#26 Remove Converted gguf Models & Enhance UI in Models Tab
  core.py
  webui.py
Labels: Feature
